const modules = [
  {name:'古诗学堂',desc:'等级、古诗内容与三个关联游戏',symbol:'诗',color:'#2eb485',tint:'#e8f8f2',status:'已发布',units:24,tasks:86,version:'V2.3'},
  {name:'启蒙英语',desc:'等级、英文儿歌与顺序游戏任务',symbol:'英',color:'#3f73df',tint:'#eaf1ff',status:'已发布',units:18,tasks:62,version:'V2.1'},
  {name:'思维逻辑',desc:'能力分类与纯游戏列表',symbol:'思',color:'#7367dd',tint:'#f0edff',status:'审核中',units:16,tasks:54,version:'V1.9'},
  {name:'玩转数学',desc:'练习类型、数字视频与游戏链',symbol:'数',color:'#25a8b8',tint:'#e8f7f8',status:'已发布',units:12,tasks:40,version:'V1.7'},
  {name:'快乐成长',desc:'主题分类、视频与关联游戏',symbol:'乐',color:'#e39342',tint:'#fff4e8',status:'草稿',units:10,tasks:28,version:'V1.3'},
  {name:'汉字闯关',desc:'等级、视频与三个顺序解锁游戏',symbol:'字',color:'#e16c87',tint:'#fff0f3',status:'已发布',units:15,tasks:47,version:'V1.6'},
  {name:'趣味百科',desc:'百科分类、知识详情与挑战游戏',symbol:'百',color:'#ef7555',tint:'#fff0eb',status:'已发布',units:11,tasks:31,version:'V1.5'},
  {name:'故事时间',desc:'故事分类、视频与独立游戏',symbol:'故',color:'#bd62c8',tint:'#f8edfa',status:'草稿',units:9,tasks:24,version:'V1.2'},
  {name:'儿歌派对',desc:'筛选分类与纯视频轮播合集',symbol:'歌',color:'#879c32',tint:'#f4f7e8',status:'已发布',units:14,tasks:38,version:'V1.4'}
];

const secondaryPages = [
  {id:'P-1001',name:'古诗学堂二级页',module:'古诗学堂',route:'/poetry',template:'等级分类页',components:3,status:'已发布',updated:'今天 11:18',owner:'运营小林',color:['#49c69a','#249976']},
  {id:'P-1002',name:'L1 启蒙级',module:'英语启蒙',route:'/english/l1',template:'横向轮播页',components:6,status:'已发布',updated:'昨天 16:42',owner:'产品小周',color:['#f2a258','#dc713d']},
  {id:'P-1003',name:'图形与颜色',module:'思维逻辑',route:'/logic/shapes',template:'路径关卡页',components:8,status:'草稿',updated:'昨天 14:20',owner:'运营小林',color:['#8375e3','#6655c8']},
  {id:'P-1004',name:'认识数字',module:'玩转数学',route:'/math/numbers',template:'视频任务页',components:7,status:'已发布',updated:'09-21 15:06',owner:'内容小王',color:['#5689ee','#3465ca']},
  {id:'P-1005',name:'健康卫生',module:'快乐成长',route:'/growth/health',template:'路径关卡页',components:9,status:'审核中',updated:'09-21 10:32',owner:'内容小王',color:['#4fb4c4','#268fa2']},
  {id:'P-1006',name:'动物百科',module:'趣味百科',route:'/encyclopedia/animals',template:'场景热点页',components:11,status:'已发布',updated:'09-20 17:25',owner:'产品小周',color:['#796fe0','#5f54c7']},
  {id:'P-1007',name:'童话故事',module:'故事时间',route:'/story/fairy-tales',template:'主题入口页',components:6,status:'草稿',updated:'09-20 11:40',owner:'运营小林',color:['#d874a1','#b95183']},
  {id:'P-1008',name:'交通工具',module:'趣味百科',route:'/encyclopedia/transport',template:'知识详情页',components:10,status:'已发布',updated:'09-19 16:08',owner:'内容小王',color:['#56bca4','#2b9b7f']}
];

let activePageIndex = 0;
const levelCategories = [
  {id:'LEVEL-01',name:'小秀才',image:'level_xiucai.png',description:'认识画面与字词，完成古诗启蒙学习',voice:'欢迎来到小秀才，先从认识画面与字词开始吧。',status:'启用'},
  {id:'LEVEL-02',name:'小举人',image:'level_juren.png',description:'补全诗句与接龙，提升古诗理解能力',voice:'小举人等你来挑战，看看你能补全几首古诗。',status:'启用'},
  {id:'LEVEL-03',name:'小状元',image:'level_zhuangyuan.png',description:'理解诗意与进阶挑战，完成综合闯关',voice:'欢迎挑战小状元，完成全部关卡即可获得金榜称号。',status:'启用'}
];
const pageLevelConfigs = {'P-1001':levelCategories};
function getPageLevels(page){
  if(!pageLevelConfigs[page.id])pageLevelConfigs[page.id]=[
    {id:'LEVEL-01',name:'启蒙级',image:'level_beginner.png',description:'适合初次进入的基础学习内容',voice:`欢迎进入${page.name}启蒙级。`,status:'启用'},
    {id:'LEVEL-02',name:'进阶级',image:'level_advanced.png',description:'完成启蒙级后解锁进阶学习内容',voice:`欢迎挑战${page.name}进阶级。`,status:'启用'},
    {id:'LEVEL-03',name:'提高级',image:'level_master.png',description:'综合能力提升与进阶挑战内容',voice:`欢迎进入${page.name}提高级。`,status:'停用'}
  ];
  return pageLevelConfigs[page.id];
}

const pageNames = {dashboard:'首页',modules:'模块管理',pages:'页面管理',pageEditor:'页面配置',composer:'内容编排',library:'内容资源库',voices:'旁白与音频库',users:'用户管理',hall:'游戏大厅',games:'游戏管理',questions:'题库',packs:'关卡包',skins:'素材与皮肤',releases:'发布管理',analytics:'运营数据'};
const workspace = document.querySelector('#workspace');
const breadcrumb = document.querySelector('#breadcrumb strong');
const modalBackdrop = document.querySelector('#modalBackdrop');
const modal = document.querySelector('#modal');

function renderDashboard(){
  workspace.innerHTML = `
    <div class="page-heading"><div><h1>下午好，内容运营团队</h1><p>今天有 2 个版本待处理、1 个导入批次存在异常，请及时跟进。</p></div><div class="heading-actions"><button class="btn" data-go="questions">查看导入记录</button><button class="btn primary" data-go="composer">＋ 新建内容编排</button></div></div>
    <div class="metrics">
      ${metric('已上线模块','9','全部模块已配置','▦','#2d66df','#edf3ff')}
      ${metric('内容任务','410','较上周 +18','⌘','#2eae82','#eaf8f3')}
      ${metric('题库总量','3,862','本周新增 240','?','#786adf','#f1efff')}
      ${metric('待发布变更','28','2 个版本待审核','⇧','#e89542','#fff4e8')}
    </div>
    <div class="dash-grid">
      <section class="card section-card"><div class="section-title"><div><h2>近 7 日内容消费趋势</h2><p>视频播放与游戏完成次数</p></div><div><span class="tiny-tag">● 视频播放</span> <span class="tiny-tag green">● 游戏完成</span></div></div><div class="flow-bar">${[48,68,55,80,67,102,93].map((v,i)=>`<div class="bar-col"><i style="height:${v*.72}px"></i><i style="height:${(v+25)*.72}px"></i></div>`).join('')}</div><div class="bar-labels">${['周一','周二','周三','周四','周五','周六','周日'].map(x=>`<span>${x}</span>`).join('')}</div></section>
      <section class="card section-card"><div class="section-title"><div><h2>模块内容完成度</h2><p>已配置内容 / 规划内容</p></div><button class="text-link" data-go="modules">全部模块 →</button></div><div class="module-progress-list">${modules.slice(0,5).map((m,i)=>`<div class="module-progress-item"><span>${m.name}</span><div class="progress"><i style="width:${[92,86,78,75,62][i]}%;--color:${m.color}"></i></div><b>${[92,86,78,75,62][i]}%</b></div>`).join('')}</div></section>
      <section class="card section-card"><div class="section-title"><div><h2>近期操作</h2><p>关键内容变更与审核记录</p></div><button class="text-link">查看日志 →</button></div><div class="activity-list">${activity('⇧','运营小林提交了版本 V2.4','快乐成长 · 18 项内容变更','12 分钟前')}${activity('✓','管理员通过了模块审核','数学思维 · V1.9','1 小时前')}${activity('⇩','题库批量导入完成','健康小卫士 · 成功 238 条','昨天 16:42')}</div></section>
      <section class="card section-card"><div class="section-title"><div><h2>待办提醒</h2><p>发布前需要处理的问题</p></div></div><div class="activity-list">${activity('!','2 条题目校验失败','批次 IMP-20260922-03','立即处理')}${activity('◷','3 个视频缺少封面','科学探索 · 昆虫世界','补充素材')}${activity('↻','旧关卡包待迁移','生活实践 · V1.1','查看方案')}</div></section>
    </div>`;
}

function metric(label,num,foot,icon,tone,tint){return `<section class="card metric-card" style="--tone:${tone};--tint:${tint}"><div class="metric-head"><span>${label}</span><i class="metric-icon">${icon}</i></div><div class="metric-number">${num}</div><div class="metric-foot"><strong>↑</strong>${foot}</div></section>`}
function activity(icon,title,sub,time){return `<div class="activity"><span class="activity-icon">${icon}</span><div><strong>${title}</strong><small>${sub}</small></div><time>${time}</time></div>`}

function renderModules(){
  workspace.innerHTML = `<div class="page-heading"><div><h1>模块管理</h1><p>二期新增功能，操作样式沿用现有欢芽后台的查询、列表与弹窗编辑模式。</p></div></div>
    <section class="card admin-list-card"><div class="admin-filter"><label>模块名称<input class="search" id="moduleSearch" placeholder="请输入模块名称或编码"/></label><label>状态<select class="select" id="moduleStatus"><option value="">请选择状态</option><option>已发布</option><option>审核中</option><option>草稿</option></select></label><button class="btn primary" id="moduleQuery">⌕ 查询</button><button class="btn" id="moduleReset">↻ 重置</button></div><div class="admin-actions"><button class="btn primary" id="addModule">＋ 添加</button><button class="btn danger" id="deleteModule">▱ 删除</button><button class="btn" id="sortModules">↕ 模块排序</button><span class="spacer"></span><span id="moduleCount">共 9 个模块</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th><i class="checkbox" data-check-all></i></th><th>模块编码</th><th>模块名称</th><th>分类数</th><th>内容数</th><th>任务数</th><th>当前版本</th><th>状态</th><th>更新时间</th><th>操作</th></tr></thead><tbody>${modules.map(moduleTableRow).join('')}</tbody></table></div><div class="pagination"><span>共 9 条</span><div class="pages"><button>‹</button><button class="active">1</button><button>›</button></div></div></section>`;
}
function moduleCard(m,i){let cls=m.status==='草稿'?'draft':m.status==='审核中'?'review':'';return `<section class="card module-card" data-module-card data-name="${m.name}" data-status="${m.status}" style="--accent:${m.color};--tint:${m.tint}"><i class="module-accent"></i><div class="module-card-head"><span class="module-symbol">${m.symbol}</span><span class="status-pill ${cls}">${m.status}</span></div><h3>${m.name}</h3><p>${m.desc}</p><div class="module-stats"><span><strong>${m.units}</strong>内容单元</span><span><strong>${m.tasks}</strong>任务节点</span><span><strong>${m.version}</strong>当前版本</span><div class="module-actions"><button class="btn small" data-edit-module="${i}">进入编排</button><button class="icon-more" data-module-more="${i}">•••</button></div></div></section>`}
function moduleTableRow(m,i){let cls=m.status==='已发布'?'green':m.status==='草稿'?'orange':'';return `<tr data-module-card data-name="${m.name}" data-status="${m.status}"><td><i class="checkbox" data-row-check></i></td><td><code class="route-code">MOD-${String(i+1).padStart(2,'0')}</code></td><td><div class="page-title-cell"><span class="page-cover" style="--from:${m.color};--to:${m.color}cc">${m.symbol}</span><div><strong>${m.name}</strong><small>${m.desc}</small></div></div></td><td>${[3,3,3,3,3,3,5,3,4][i]}</td><td>${m.units}</td><td>${m.tasks}</td><td>${m.version}</td><td><span class="tiny-tag ${cls}">${m.status}</span></td><td>2026-09-${29-i}<br><small style="color:#9aa4b3">运营小林</small></td><td><button class="table-action" data-edit-module-meta="${i}">编辑</button><button class="table-action" data-edit-module="${i}">内容编排</button><button class="table-action" data-module-more="${i}">更多</button></td></tr>`}

function renderPages(){
  workspace.innerHTML=`<div class="page-heading"><div><h1>页面管理</h1><p>二期新增页面配置入口，沿用现有后台列表查询、批量操作和弹窗新增逻辑。</p></div></div>
    <section class="card admin-list-card"><div class="admin-filter"><label>页面名称<input class="search" id="pageSearch" placeholder="请输入页面名称、编码或路由"></label><label>所属模块<select class="select" id="pageModule"><option value="">请选择模块</option><option>古诗学堂</option><option>英语启蒙</option><option>思维逻辑</option><option>玩转数学</option><option>快乐成长</option><option>趣味百科</option><option>故事时间</option></select></label><label>状态<select class="select" id="pageStatus"><option value="">请选择状态</option><option>已发布</option><option>审核中</option><option>草稿</option></select></label><button class="btn primary" id="pageQuery">⌕ 查询</button><button class="btn" id="pageReset">↻ 重置</button></div><div class="admin-actions"><button class="btn primary" id="newPage">＋ 添加</button><button class="btn danger" id="deletePage">▱ 删除</button><button class="btn" id="copyPage">▣ 复制</button><button class="btn" id="pageSort">↕ 页面排序</button><span class="spacer"></span><span>二期新增</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th><i class="checkbox" data-check-all></i></th><th>页面名称</th><th>所属模块</th><th>页面路由</th><th>页面类型</th><th>分类数</th><th>状态</th><th>更新信息</th><th>操作</th></tr></thead><tbody id="pageTableBody">${secondaryPages.map(pageRow).join('')}</tbody></table></div><div class="pagination"><span id="pageCount">共 36 个页面 · 当前展示 8 个</span><div class="pages"><button>‹</button><button class="active">1</button><button>2</button><button>3</button><button>›</button></div></div></section>`;
}
function pageRow(p,i){let cls=p.status==='已发布'?'green':p.status==='草稿'?'orange':'';return `<tr class="row-click" data-page-row data-name="${p.name}" data-module="${p.module}" data-status="${p.status}" data-route="${p.route}"><td><i class="checkbox" data-row-check></i></td><td><div class="page-title-cell"><span class="page-cover" style="--from:${p.color[0]};--to:${p.color[1]}">${p.name.slice(0,1)}</span><div><strong>${p.name}</strong><small>${p.id}</small></div></div></td><td>${p.module}</td><td><code class="route-code">${p.route}</code></td><td>${p.template}</td><td>${p.components}</td><td><span class="tiny-tag ${cls}">${p.status}</span></td><td>${p.owner}<br><small style="color:#9aa4b3">${p.updated}</small></td><td><button class="table-action" data-page-edit="${i}">编辑/装修</button><button class="table-action" data-page-more="${i}">更多</button></td></tr>`}

function renderPageBuilder(){
  const page=secondaryPages[activePageIndex]||secondaryPages[0];
  const isPoetry=page.module==='古诗学堂';
  const levels=getPageLevels(page);
  const voice=isPoetry?'欢迎来到古诗学堂，请选择小秀才、小举人或小状元开始学习。':`欢迎来到${page.name}，请选择一个等级开始学习。`;
  workspace.innerHTML=`<div class="page-heading"><div><h1>二级页面配置 · ${page.name}</h1><p>${page.module} / ${page.id} · 最近保存：今天 11:18</p></div><div class="heading-actions"><button class="btn" data-go="pages">← 返回页面管理</button><button class="btn" id="savePageDraft">保存草稿</button><button class="btn primary" id="savePage">保存并提交</button></div></div>
    <div class="page-config-layout">
      <section class="card config-card">
        <div class="config-card-head"><div><h2>基础信息</h2><p>配置二级页面名称、归属及前端路由。</p></div><span class="tiny-tag green">${page.status}</span></div>
        <div class="config-card-body form-grid-3">
          <div class="field"><label><b class="required">*</b> 页面名称</label><input id="configPageName" value="${page.name}"></div>
          <div class="field"><label>所属模块</label><select><option>${page.module}</option></select></div>
          <div class="field"><label>页面编码</label><input value="${page.id}" disabled></div>
          <div class="field"><label>页面层级</label><select><option>二级页面</option></select></div>
          <div class="field"><label>页面类型</label><select><option>等级分类页</option><option>主题分类页</option></select></div>
          <div class="field"><label>页面路由</label><input value="${page.route}"></div>
        </div>
      </section>

      <section class="card config-card">
        <div class="config-card-head"><div><h2>页面素材与旁白</h2><p>配置二级页面背景素材、进入旁白及播放规则。</p></div><button class="btn small" data-go="voices">进入旁白库</button></div>
        <div class="config-card-body media-config-grid">
          <div class="field"><label><b class="required">*</b> 页面背景图</label><div class="upload-field"><div class="asset-thumb background-asset">背景图</div><div class="upload-meta"><strong>${isPoetry?'bg_poetry_hall.png':'bg_secondary_page.png'}</strong><span>建议尺寸 1920 × 1080，PNG/JPG，≤ 5MB</span><div><button class="btn small" data-select-asset="background">从素材库选择</button><button class="btn small" data-upload-asset="background">本地上传</button></div></div></div></div>
          <div class="field narration-field"><label><b class="required">*</b> 页面进入旁白</label><textarea id="pageVoiceText">${voice}</textarea><div class="inline-form-row"><select><option>每次进入播放</option><option>每次会话首次播放</option></select><select><option>页面加载后立即</option><option>页面加载后 0.8 秒</option></select><button class="btn small" data-speak-source="pageVoiceText">▶ 试听</button></div><small class="field-help">可直接填写文案生成语音，也可在旁白库绑定已上传音频。</small></div>
        </div>
      </section>

      <section class="card config-card level-config-card">
        <div class="config-card-head"><div><h2>等级分类</h2><p>配置二级页面展示的等级入口；前端按排序从左到右展示。</p></div><button class="btn primary" id="addLevel">＋ 新增等级分类</button></div>
        <div class="table-wrap"><table class="data-table level-table"><thead><tr><th>排序</th><th>等级分类图片</th><th>等级分类名称</th><th>分类编码</th><th>分类说明</th><th>分类旁白</th><th>状态</th><th>操作</th></tr></thead><tbody id="levelTableBody">${levels.map(levelRow).join('')}</tbody></table></div>
        <div class="config-note"><span>ⓘ</span><span>等级分类仅定义二级页面入口。点击“配置内容”可继续关联该等级下的视频、游戏和列表页数据。</span></div>
      </section>
    </div>`;
}
function levelRow(level,index){return `<tr data-level-row="${index}"><td><button class="drag-handle" aria-label="拖拽排序">☷</button> ${index+1}</td><td><div class="level-image-cell"><span class="level-thumb">${level.name.slice(1,2)||level.name.slice(0,1)}</span><div><strong>${level.image}</strong><small>372 × 231</small></div></div></td><td><strong>${level.name}</strong></td><td><code class="route-code">${level.id}</code></td><td class="level-description">${level.description}</td><td class="level-description">${level.voice}</td><td><span class="tiny-tag ${level.status==='启用'?'green':'orange'}">${level.status}</span></td><td><button class="table-action" data-edit-level="${index}">编辑</button><button class="table-action" data-config-level="${index}">配置内容</button><button class="table-action danger-text" data-delete-level="${index}">删除</button></td></tr>`}
function levelEditModal(index){
  const page=secondaryPages[activePageIndex]||secondaryPages[0];
  const levels=getPageLevels(page);const level=index===undefined?null:levels[index];
  openModal(`<div class="modal-head"><h2>${level?'编辑':'新增'}等级分类</h2><button class="modal-close" data-close>×</button></div><div class="modal-body"><div class="field-row"><div class="field"><label><b class="required">*</b> 等级分类名称</label><input id="levelNameDraft" value="${level?.name||''}" placeholder="如：小秀才"></div><div class="field"><label>分类编码</label><input id="levelCodeDraft" value="${level?.id||`LEVEL-0${levels.length+1}`}" ${level?'disabled':''}></div></div><div class="field"><label><b class="required">*</b> 等级分类图片</label><div class="upload-field modal-upload-field"><div class="asset-thumb level-asset">${level?.name?.slice(1,2)||'图'}</div><div class="upload-meta"><strong id="levelImageName">${level?.image||'暂未选择图片'}</strong><span>建议尺寸 372 × 231，PNG/JPG，≤ 2MB</span><div><button class="btn small" data-select-asset="level">从素材库选择</button><button class="btn small" data-upload-asset="level">本地上传</button></div></div></div></div><div class="field"><label>分类说明</label><textarea id="levelDescriptionDraft" placeholder="用于运营后台识别该等级内容">${level?.description||''}</textarea></div><div class="field"><label>等级分类旁白</label><textarea id="levelVoiceDraft" placeholder="焦点落在该等级入口时播报">${level?.voice||''}</textarea><small class="field-help">用于遥控器焦点落在分类入口时播报。</small></div><div class="field-row"><div class="field"><label>状态</label><select id="levelStatusDraft"><option ${level?.status!=='停用'?'selected':''}>启用</option><option ${level?.status==='停用'?'selected':''}>停用</option></select></div><div class="field"><label>排序</label><input type="number" value="${index===undefined?levels.length+1:index+1}"></div></div><input type="hidden" id="editingLevelIndex" value="${index===undefined?'':index}"></div><div class="modal-foot"><button class="btn" data-close>取 消</button><button class="btn primary" id="saveLevel">确 定</button></div>`,true)
}
function templateMini(icon,name,type,active=false){return `<button class="template-mini ${active?'active':''}" data-template-demo="${type}"><i>${icon}</i><span>${name}</span></button>`}
function componentItem(icon,name,type){return `<button class="component-item" data-add-component="${type}"><i>${icon}</i>${name}</button>`}
function phoneTask(icon,title,meta,bg,color){return `<div class="task-preview"><div class="task-img" style="--bg:${bg};--color:${color}">${icon}</div><div><strong>${title}</strong><small>${meta}</small></div><b>去学习</b></div>`}

function renderComposer(){
  workspace.innerHTML = `<div class="page-heading"><div><h1>内容编排</h1><p>按“模块 → 分类 → 内容单元 → 任务节点”组织前端内容；视频和游戏可在同一单元内混排。</p></div><div class="heading-actions"><button class="btn" id="previewModule">◉ 前端预览</button><button class="btn" id="saveDraft">保存草稿</button><button class="btn primary" id="submitReview">提交审核</button></div></div>
    <div class="composer-layout">
      <aside class="panel tree-panel"><div class="panel-head"><strong>内容结构</strong><button class="icon-more">＋</button></div><div class="panel-search"><input class="search" placeholder="搜索内容单元"/></div><div class="tree">
        <div class="tree-row"><span class="caret">▼</span><span class="tree-ico">芽</span>快乐成长<span class="count">24</span></div>
        <div class="tree-row tree-indent-1"><span class="caret">▼</span><span class="tree-ico">类</span>健康卫生<span class="count">8</span></div>
        <div class="tree-row tree-indent-2 active"><span class="caret">▼</span><span class="tree-ico">单</span>保护眼睛<span class="count">4</span></div>
        <div class="tree-row tree-indent-3"><span class="caret">·</span><span class="tree-ico">单</span>牙齿保卫战<span class="count">5</span></div>
        <div class="tree-row tree-indent-3"><span class="caret">·</span><span class="tree-ico">单</span>洗手七步法<span class="count">3</span></div>
        <div class="tree-row tree-indent-1"><span class="caret">▶</span><span class="tree-ico">类</span>安全意识<span class="count">7</span></div>
        <div class="tree-row tree-indent-1"><span class="caret">▶</span><span class="tree-ico">类</span>行为习惯<span class="count">9</span></div>
      </div></aside>
      <section class="panel composer-main"><div class="composer-top"><div class="composer-title"><span class="big-symbol">眼</span><div><h2>保护眼睛</h2><p>单元编码：KLG-HY-001 · 适用年龄：4—6 岁 · 共 4 个任务</p></div></div><div><span class="status-pill draft">编辑中</span></div></div>
        <div class="chain"><div class="chain-summary"><strong>任务路径</strong><span>完成上一个任务后解锁下一个 · 拖拽可排序</span></div>
          ${chainItem(1,'video','为什么眼睛会近视？','科普视频','03:28','必修','#e5f2ff','#3c79de',true)}<div class="chain-connector"></div>
          ${chainItem(2,'game','视力小卫士','配对游戏','6 个关卡','需达 60 分','#eaf8f2','#2ba87d')}<div class="chain-connector"></div>
          ${chainItem(3,'video','护眼操一起做','跟练视频','02:10','必修','#fff2e7','#df8b3d')}<div class="chain-connector"></div>
          ${chainItem(4,'game','找出伤眼行为','判断游戏','8 道题','不限次数','#f0edff','#7766d8')}
          <button class="add-node" id="addTask">＋ 添加视频或游戏任务</button>
        </div></section>
      <aside class="panel inspector"><div class="panel-head"><div><strong>任务属性</strong><small style="display:block;margin-top:3px">当前：为什么眼睛会近视？</small></div><button class="icon-more">•••</button></div><div class="inspector-grid">
        <div class="inspector-section"><h3>基础信息</h3><div class="field"><label>任务名称</label><input value="为什么眼睛会近视？"></div><div class="field"><label>内容类型</label><select><option>视频</option><option>游戏</option></select></div><div class="field"><label>引导语</label><textarea>跟着芽芽一起看看，眼睛是怎样工作的吧！</textarea></div></div>
        <div class="inspector-section"><h3>学习与解锁规则</h3><div class="field-row"><div class="field"><label>任务序号</label><input value="1"></div><div class="field"><label>预计时长</label><input value="3 分钟"></div></div><div class="switch-row"><span>设为必修任务</span><i class="switch on"></i></div><div class="switch-row"><span>完成后自动解锁</span><i class="switch on"></i></div><div class="switch-row"><span>允许重复学习</span><i class="switch on"></i></div></div>
        <div class="inspector-section"><h3>发布前检查</h3><div class="quality-list"><div class="quality"><i></i>基础字段完整<span>已通过</span></div><div class="quality"><i></i>视频资源可用<span>已通过</span></div><div class="quality"><i></i>封面尺寸合规<span>已通过</span></div><div class="quality warn"><i></i>无障碍字幕<span>建议补充</span></div></div></div>
      </div></aside>
    </div>`;
}
function chainItem(n,type,title,kind,meta,rule,bg,color,selected=false){return `<article class="chain-item ${selected?'selected':''}"><span class="drag">⋮⋮</span><div class="content-thumb ${type==='video'?'video':''}" style="--bg:${bg};--color:${color}">${type==='game'?'◇':''}</div><div class="content-body"><h4><span class="type-tag" style="--tagbg:${bg};--tagcolor:${color}">${type==='video'?'视频':'游戏'}</span> ${n}. ${title}</h4><div class="content-meta"><span>类型 <b>${kind}</b></span><span>${type==='video'?'时长':'内容'} <b>${meta}</b></span><span>规则 <b>${rule}</b></span></div></div><div class="chain-actions"><button>✎</button><button>⋯</button></div></article>`}

function renderQuestions(){
  workspace.innerHTML = `<div class="page-heading"><div><h1>题库</h1><p>保留现有逐题配置、审核和打包流程，二期仅在列表操作区新增导入、导出与导入记录。</p></div></div>
    <section class="card admin-list-card"><div class="admin-filter"><label>题目编号<input class="search" placeholder="请输入题目编号"></label><label>题目文字<input class="search" placeholder="请输入题目文字"></label><label>所属游戏<select class="select"><option>请选择游戏</option><option>汉字打怪兽</option><option>视力小卫士</option></select></label><label>审核状态<select class="select"><option>请选择审核状态</option><option>待审核</option><option>已审核</option></select></label><label>来源<select class="select"><option>请选择来源</option><option>手动</option><option>批量导入</option></select></label><button class="btn primary">⌕ 查询</button><button class="btn">↻ 重置</button></div><div class="admin-actions question-actions"><button class="btn primary" id="addQuestion">＋ 添加</button><button class="btn danger">▱ 删除</button><button class="btn audit">♟ 批量审核</button><button class="btn pack">▣ 打包成关卡包</button><button class="btn" id="importQuestions">⇧ 导入</button><button class="btn" id="exportQuestions">⇩ 导出</button><button class="btn" id="viewBatch">导入记录</button></div><div class="table-wrap"><table class="data-table question-current-table"><thead><tr><th><i class="checkbox"></i></th><th>题目编号</th><th>题目文字</th><th>所属游戏</th><th>所属关卡包</th><th>难度等级</th><th>适用年龄</th><th>背景图</th><th>来源</th><th>审核状态</th><th>创建时间</th><th>操作</th></tr></thead><tbody>
        ${questionRow('2104828633482108929','北、比','汉字打怪兽','汉字闯关-Lv.1人小人大会变身','1','0-2','手动','待审核','2026-09-29 15:00')}
        ${questionRow('2104828404502470658','大','汉字百变秀','汉字闯关-Lv.1人小人大会变身','15','0-2','手动','已审核','2026-09-29 14:59')}
        ${questionRow('2104755435730124801','小朋友能做的助人小事？','礼仪小达人','友爱礼仪第3关-乐于助人','4','4-6','手动','已审核','2026-09-29 10:09')}
        ${questionRow('2104755212639289345','帮助别人后心情如何？','礼仪小达人','友爱礼仪第3关-乐于助人','4','4-6','批量导入','已审核','2026-09-29 10:08')}
        ${questionRow('2104754902764109826','哪种行为是乐于助人？','礼仪小达人','友爱礼仪第3关-乐于助人','4','4-6','批量导入','已审核','2026-09-29 10:07')}
      </tbody></table></div><div class="pagination"><span>共 417 条</span><div class="pages"><button>‹</button><button class="active">1</button><button>2</button><button>3</button><button>4</button><button>5</button><button>…</button><button>21</button><button>›</button></div></div></section>`;
}
function questionRow(id,q,game,pack,level,age,source,status,date){return `<tr><td><i class="checkbox"></i></td><td><span class="id-cell">${id}</span></td><td>${q}</td><td>${game}</td><td>${pack}</td><td>${level}</td><td>${age}</td><td><span class="question-bg">▧</span></td><td><span class="tiny-tag">${source}</span></td><td><span class="tiny-tag ${status==='已审核'?'green':'orange'}">${status}</span></td><td>${date}</td><td><button class="table-action">编辑</button><button class="table-action">审核</button><button class="table-action">复制</button></td></tr>`}

function renderReleases(){
  workspace.innerHTML = `<div class="page-heading"><div><h1>发布管理</h1><p>将模块、内容任务、游戏与题库变更汇总为版本，完成校验和审核后统一发布。</p></div><div class="heading-actions"><button class="btn">发布规则</button><button class="btn primary" id="createRelease">＋ 创建发布版本</button></div></div>
    <section class="card release-banner"><span class="release-icon">⇧</span><div><h3>V2.4 已通过审核，等待发布</h3><p>包含 4 个模块、18 项内容变更与 240 道题目 · 预计影响 12,480 名用户</p></div><button class="btn" id="validateRelease">运行上线校验</button><button class="btn primary" id="publishRelease">立即发布</button></section>
    <section class="card table-card"><div class="table-toolbar"><input class="search" placeholder="搜索版本号或说明"><select class="select"><option>全部状态</option><option>待发布</option><option>审核中</option><option>已发布</option></select><div class="spacer"></div><span style="font-size:10px;color:#8a95a6">生产环境 · 最近发布于 09-18 17:30</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>版本</th><th>版本说明</th><th>变更摘要</th><th>上线校验</th><th>状态</th><th>创建人</th><th>创建时间</th><th>操作</th></tr></thead><tbody>
      ${releaseRow('V2.4','秋季内容优化与题库扩充',['4 模块','18 内容','240 题'],'12/12 项通过','待发布','运营小林','今天 11:06')}
      ${releaseRow('V2.3','快乐成长模块内容调整',['1 模块','6 内容','40 题'],'12/12 项通过','已发布','产品小周','09-18 16:42')}
      ${releaseRow('V2.2','数学思维关卡包升级',['2 模块','9 内容','86 题'],'11/12 项通过','已回滚','运营小林','09-12 14:20')}
      ${releaseRow('V2.1','二期框架首版迁移',['9 模块','186 内容','1,240 题'],'12/12 项通过','已发布','管理员','09-01 10:00')}
    </tbody></table></div><div class="pagination"><span>共 14 个版本</span><div class="pages"><button>‹</button><button class="active">1</button><button>2</button><button>›</button></div></div></section>`;
}
function releaseRow(v,n,diff,check,status,user,date){let cls=status==='待发布'?'orange':status==='已发布'?'green':'';return `<tr><td><div class="version">${v}<small>正式版本</small></div></td><td>${n}</td><td><div class="diff-list">${diff.map(x=>`<span>${x}</span>`).join('')}</div></td><td><span class="validation ${check.startsWith('12')?'':'warn'}"><i></i>${check}</span></td><td><span class="tiny-tag ${cls}">${status}</span></td><td>${user}</td><td>${date}</td><td><button class="table-action">查看</button><button class="table-action">${status==='已发布'?'回滚':'编辑'}</button></td></tr>`}

function renderVoices(){
  const voices=[
    ['VO-1001','欢迎来到健康卫生，请选择你想学习的主题。','页面进入旁白','健康卫生','真人录音','00:06','已启用'],
    ['VO-1002','保护眼睛，进行中，已完成一个任务，共十个任务。','焦点播报','保护眼睛','动态 TTS','00:07','已启用'],
    ['VO-1003','按左右键选择主题，按确认键进入。','空闲提醒','健康卫生','真人录音','00:05','已启用'],
    ['VO-1004','完成上一任务后解锁。','锁定提示','任务节点','动态 TTS','00:03','已启用'],
    ['VO-1005','欢迎来到古诗学堂，选一首古诗开始学习吧。','页面进入旁白','古诗学堂','真人录音','00:07','待审核']
  ];
  workspace.innerHTML=`<div class="page-heading"><div><h1>旁白与音频库</h1><p>复用现有 AI 生成语音和上传音频能力，二期增加页面、焦点、状态与空闲提醒的绑定关系。</p></div></div><section class="card admin-list-card"><div class="admin-filter"><label>旁白编号<input class="search" id="voiceSearch" placeholder="请输入编号或旁白文案"></label><label>旁白用途<select class="select"><option>请选择用途</option><option>页面进入旁白</option><option>焦点播报</option><option>空闲提醒</option><option>锁定提示</option></select></label><label>绑定模块<select class="select"><option>请选择模块</option><option>快乐成长</option><option>古诗学堂</option></select></label><label>状态<select class="select"><option>请选择状态</option><option>已启用</option><option>待审核</option></select></label><button class="btn primary">⌕ 查询</button><button class="btn">↻ 重置</button></div><div class="admin-actions"><button class="btn primary" id="newVoice">＋ 添加</button><button class="btn danger">▱ 删除</button><button class="btn" id="voiceImport">⇧ 批量导入</button><button class="btn" id="voiceExport">⇩ 导出脚本</button><button class="btn" data-go="pageEditor">页面配置</button><span class="spacer"></span><span>页面级旁白＋元素级旁白</span></div><div class="table-wrap"><table class="data-table voice-table"><thead><tr><th>试听</th><th>旁白文案</th><th>用途</th><th>绑定对象</th><th>生成方式</th><th>时长</th><th>状态</th><th>操作</th></tr></thead><tbody>${voices.map(v=>voiceRow(v)).join('')}</tbody></table></div><div class="pagination"><span>共 48 条</span><div class="pages"><button>‹</button><button class="active">1</button><button>2</button><button>›</button></div></div></section>`;
}
function voiceRow(v){return `<tr data-voice-row data-text="${v[1]}"><td><button class="voice-play" data-speak="${v[1]}">▶</button></td><td><div class="voice-copy"><strong>${v[1]}</strong><small>${v[0]}</small></div></td><td><span class="tiny-tag">${v[2]}</span></td><td>${v[3]}</td><td>${v[4]}</td><td>${v[5]}</td><td><span class="tiny-tag ${v[6]==='已启用'?'green':'orange'}">${v[6]}</span></td><td><button class="table-action" data-edit-voice>编辑</button><button class="table-action" data-speak="${v[1]}">试听</button></td></tr>`}

function speakText(text){
  if(!text)return;
  if(!('speechSynthesis' in window)){toast('当前浏览器不支持语音试听','旁白文案仍可正常配置');return}
  window.speechSynthesis.cancel();
  const utterance=new SpeechSynthesisUtterance(text);utterance.lang='zh-CN';utterance.rate=.92;utterance.pitch=1.04;
  const voice=window.speechSynthesis.getVoices().find(v=>/zh|Chinese|中文/i.test(`${v.lang} ${v.name}`));if(voice)utterance.voice=voice;
  window.speechSynthesis.speak(utterance);toast('正在试听旁白',text.length>28?`${text.slice(0,28)}…`:text);
}

function newVoiceModal(text=''){
  openModal(`<div class="modal-head"><h2>${text?'编辑':'新建'}旁白</h2><button class="modal-close" data-close>×</button></div><div class="modal-body"><div class="field"><label>旁白用途</label><select><option>页面进入旁白</option><option>焦点播报</option><option>空闲提醒</option><option>锁定提示</option></select></div><div class="field"><label>旁白文案</label><textarea id="voiceDraft" style="height:92px">${text||'欢迎来到健康卫生，请选择你想学习的主题。'}</textarea></div><div class="field-row"><div class="field"><label>生成方式</label><select><option>动态 TTS</option><option>上传真人录音</option></select></div><div class="field"><label>绑定对象</label><select><option>健康卫生</option><option>保护眼睛</option><option>全局默认</option></select></div></div><div class="template-tip"><span>ⓘ</span><span>焦点播报支持 {title}、{status}、{completed}、{total} 动态变量。</span><button id="modalVoicePlay" data-speak-source="voiceDraft">▶ 试听</button></div></div><div class="modal-foot"><button class="btn" data-close>取消</button><button class="btn primary" id="saveVoice">保存旁白</button></div>`)
}

function renderPlaceholder(page){
  if(page==='analytics'){
    workspace.innerHTML=`<div class="page-heading"><div><h1>运营数据</h1><p>从模块、页面、内容和游戏四个维度观察前端内容效果。</p></div><div class="heading-actions"><select class="select"><option>近 7 天</option><option>近 30 天</option></select><button class="btn">⇩ 导出报表</button></div></div><div class="metrics">${metric('页面访问用户','12,480','较上周 +12.6%','人','#2d66df','#edf3ff')}${metric('任务完成率','78.4%','较上周 +4.2%','✓','#2eae82','#eaf8f3')}${metric('游戏通关率','64.8%','较上周 +2.1%','◇','#786adf','#f1efff')}${metric('人均学习时长','18m 26s','较上周 +1m 08s','◷','#e89542','#fff4e8')}</div><div class="dash-grid"><section class="card section-card"><div class="section-title"><div><h2>模块访问趋势</h2><p>访问用户与任务完成次数</p></div><button class="text-link">查看明细 →</button></div><div class="flow-bar">${[52,64,58,76,82,106,96].map(v=>`<div class="bar-col"><i style="height:${v*.68}px"></i><i style="height:${(v+22)*.68}px"></i></div>`).join('')}</div><div class="bar-labels">${['周一','周二','周三','周四','周五','周六','周日'].map(x=>`<span>${x}</span>`).join('')}</div></section><section class="card section-card"><div class="section-title"><div><h2>热门二级页面</h2><p>按访问人数排序</p></div></div><div class="module-progress-list">${['健康卫生','识字启蒙','数感启蒙','安全意识','自然观察'].map((x,i)=>`<div class="module-progress-item"><span>${x}</span><div class="progress"><i style="width:${[94,87,79,71,63][i]}%"></i></div><b>${[3280,2904,2540,2318,1986][i]}</b></div>`).join('')}</div></section></div>`;return
  }
  const configs={
    users:{title:'用户管理',desc:'沿用现有用户查询和进度查看能力，二期补充模块、分类与内容完成维度。',primary:'导出用户',columns:['用户ID','总星星','完成模块','最近游戏','最近登录','状态','操作'],rows:[['10001862','126','快乐成长 3/3','视力小卫士','今天 16:20','正常'],['10001528','98','古诗学堂 8/15','古诗拼图','今天 14:06','正常'],['10001203','76','思维逻辑 2/3','图形小达人','昨天 20:32','正常']]},
    hall:{title:'游戏大厅',desc:'保留现有入口，二期将模块首页展示配置迁移至“模块管理”。',primary:'新增展示项',columns:['展示名称','入口类型','关联模块','排序','状态','更新时间','操作'],rows:[['欢芽成长岛','模块入口','全部模块','1','已启用','今天 10:18'],['快乐成长','模块入口','快乐成长','2','已启用','昨天 16:42']]},
    library:{title:'内容资源库',desc:'统一维护视频、音频、图文和封面素材，供页面与内容编排复用。',primary:'上传资源',columns:['资源名称','资源类型','所属标签','使用次数','状态','更新时间','操作'],rows:[['眼睛的秘密','视频 · 03:28','健康卫生','8','可用','今天 10:18'],['护眼操一起做','视频 · 02:10','健康卫生','6','可用','昨天 16:42'],['芽芽角色封面','图片 · 1920×1080','公共素材','14','可用','09-20 15:06'],['健康好习惯','音频 · 00:38','健康卫生','3','转码中','09-20 11:22']]},
    games:{title:'游戏管理',desc:'维护前端游戏实例、路由参数与适用年龄，并关联关卡包和二级页面。',primary:'新建游戏',columns:['游戏名称','游戏类型','前端路由','关联关卡包','适用年龄','状态','操作'],rows:[['视力小卫士','配对游戏','/game/eye-guard','6','4—6 岁','已启用'],['找出伤眼行为','判断游戏','/game/eye-choice','8','4—6 岁','已启用'],['牙齿保卫战','闯关游戏','/game/tooth-guard','10','3—6 岁','已启用'],['数字城堡','组合游戏','/game/number-castle','12','5—6 岁','草稿']]},
    packs:{title:'关卡包',desc:'按游戏实例组织关卡、通关条件和题目范围，支持版本化管理。',primary:'新建关卡包',columns:['关卡包名称','关联游戏','关卡数','题目数','通关规则','版本','状态','操作'],rows:[['视力小卫士 · 基础包','视力小卫士','6','48','累计 60 分','V2.1','已发布'],['伤眼行为判断包','找出伤眼行为','8','64','正确率 70%','V1.6','已发布'],['牙齿保卫战 · 进阶','牙齿保卫战','10','80','获得 3 颗星','V1.3','审核中'],['数字城堡 · 8 的分合','数字城堡','6','36','完成全部关卡','V1.0','草稿']]},
    skins:{title:'素材与皮肤',desc:'沿用现有七项皮肤模板，并将页面背景、封面、旁白等通用资源接入内容资源库。',primary:'新增皮肤',columns:['皮肤名称','关联游戏','素材完整度','使用次数','状态','更新时间','操作'],rows:[['汉字闯关默认皮肤','汉字打怪兽','7/7','12','已上线','今天 10:18'],['健康小卫士蓝色皮肤','视力小卫士','7/7','6','已上线','昨天 16:42'],['古诗学堂春日皮肤','古诗拼图','6/7','0','草稿','09-20 15:06']]}
  };
  const c=configs[page];workspace.innerHTML=`<div class="page-heading"><div><h1>${c.title}</h1><p>${c.desc}</p></div><div class="heading-actions"><button class="btn">批量操作 ⌄</button><button class="btn primary">＋ ${c.primary}</button></div></div><section class="card table-card"><div class="table-toolbar"><input class="search" placeholder="搜索名称或编码"><select class="select"><option>全部状态</option><option>已发布</option><option>草稿</option></select><div class="spacer"></div><button class="btn small">⇩ 导出</button></div><div class="table-wrap"><table class="data-table"><thead><tr>${c.columns.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${c.rows.map(row=>`<tr>${row.map((v,i)=>`<td>${i===0?`<strong>${v}</strong>`:v}</td>`).join('')}<td><button class="table-action">编辑</button><button class="table-action">更多</button></td></tr>`).join('')}</tbody></table></div><div class="pagination"><span>共 ${c.rows.length} 条演示数据</span><div class="pages"><button>‹</button><button class="active">1</button><button>›</button></div></div></section>`
}

function navigate(page){
  document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===page));
  breadcrumb.textContent=pageNames[page];
  const group=['games','questions','packs','skins','users','hall'].includes(page)?'游戏运营':['releases','analytics'].includes(page)?'发布与数据':'内容运营';
  breadcrumb.innerHTML=`<span>${group}</span><b>/</b><strong>${pageNames[page]}</strong>`;
  const activeTab=document.querySelector('#activeTab');if(activeTab)activeTab.textContent=pageNames[page];
  if(page==='dashboard')renderDashboard();else if(page==='modules')renderModules();else if(page==='pages')renderPages();else if(page==='pageEditor')renderPageBuilder();else if(page==='composer')renderComposer();else if(page==='voices')renderVoices();else if(page==='questions')renderQuestions();else if(page==='releases')renderReleases();else renderPlaceholder(page);
  document.querySelector('#sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});
}

function openModal(content,wide=false){modal.className=`modal${wide?' wide':''}`;modal.innerHTML=content;modalBackdrop.classList.add('open');modalBackdrop.setAttribute('aria-hidden','false')}
function closeModal(){modalBackdrop.classList.remove('open');modalBackdrop.setAttribute('aria-hidden','true')}
function toast(title,detail){let el=document.createElement('div');el.className='toast';el.innerHTML=`<i>✓</i><div><strong>${title}</strong><p>${detail}</p></div>`;document.querySelector('#toastStack').append(el);setTimeout(()=>el.remove(),3600)}

function importModal(step=1){
  const steps=`<div class="stepper"><div class="step ${step>=1?'active':''} ${step>1?'done':''}"><i>${step>1?'✓':'1'}</i>上传文件</div><span class="step-line"></span><div class="step ${step>=2?'active':''} ${step>2?'done':''}"><i>${step>2?'✓':'2'}</i>数据校验</div><span class="step-line"></span><div class="step ${step>=3?'active':''}"><i>3</i>确认导入</div></div>`;
  let body='';let foot='';
  if(step===1){body=`${steps}<div class="dropzone"><div><span class="upload-icon">⇧</span><strong>拖拽 XLSX 或 ZIP 文件到这里</strong><p>支持题目、选项、答案、解析及图片资源；单次最多 5,000 道题</p><button class="btn small" id="chooseSample">选择文件</button></div></div><div class="template-tip"><span>ⓘ</span><span>首次导入请使用标准字段模板，避免校验失败</span><button>下载导入模板.xlsx</button></div>`;foot=`<button class="btn" data-close>取消</button><button class="btn primary" id="nextImport">下一步：开始校验</button>`}
  if(step===2){body=`${steps}<div class="file-row"><span class="file-symbol">XLSX</span><div><strong>健康卫生专项题库_0922.xlsx</strong><small>1.8 MB · 240 条数据 · 12 张图片</small></div><span class="ok">✓ 上传完成</span></div><div class="check-summary"><div class="check-box"><span>数据总数</span><strong>240</strong></div><div class="check-box"><span>校验通过</span><strong>238</strong></div><div class="check-box warn"><span>警告</span><strong>3</strong></div><div class="check-box error"><span>错误</span><strong>2</strong></div></div><div class="error-list"><div class="error-row"><b>第 26 行</b><span>正确答案未匹配到选项编码</span><em>必须修正</em></div><div class="error-row"><b>第 138 行</b><span>题目编号 Q-3741 已存在</span><em>必须修正</em></div><div class="error-row"><b style="color:#cb8739">第 82 行</b><span>题目解析为空，可导入后补充</span><em>警告</em></div></div>`;foot=`<button class="btn" id="backImport">上一步</button><button class="btn" id="exportErrors">导出错误明细</button><button class="btn primary" id="confirmImport">忽略警告，导入 238 条</button>`}
  if(step===3){body=`${steps}<div style="text-align:center;padding:18px 20px 25px"><div class="upload-icon" style="background:#e9f8f3;color:#2eaa7e">✓</div><h3 style="margin:12px 0 7px;font-size:16px">题库导入完成</h3><p style="color:#8490a3;font-size:11px;line-height:1.7">成功导入 238 条，失败 2 条。系统已生成批次记录<br>IMP-20260922-04，可在 24 小时内整批回滚。</p></div><div class="check-summary"><div class="check-box"><span>新增题目</span><strong>226</strong></div><div class="check-box"><span>更新题目</span><strong>12</strong></div><div class="check-box"><span>失败</span><strong style="color:#df5560">2</strong></div><div class="check-box"><span>耗时</span><strong>18s</strong></div></div>`;foot=`<button class="btn" id="downloadReport">下载导入报告</button><button class="btn primary" data-close>完成</button>`}
  openModal(`<div class="modal-head"><h2>批量导入题库</h2><button class="modal-close" data-close>×</button></div><div class="modal-body">${body}</div><div class="modal-foot">${foot}</div>`);
}

function resourceModal(){openModal(`<div class="modal-head"><h2>添加内容任务</h2><button class="modal-close" data-close>×</button></div><div class="modal-body"><div class="resource-tabs"><button class="active">视频资源</button><button>游戏实例</button><button>音频</button><button>图文</button></div><div style="display:flex;gap:9px;margin-bottom:13px"><input class="search" style="flex:1;width:auto" placeholder="搜索资源名称"><select class="select"><option>全部标签</option><option>健康卫生</option></select></div><div class="resource-grid">${resource('眼睛的秘密','科普视频 · 03:28','#e5f2ff','#3772d8',true)}${resource('护眼操一起做','跟练视频 · 02:10','#fff1e6','#da863b')}${resource('户外活动好处多','动画视频 · 04:06','#eaf8f2','#299c76')}${resource('正确的阅读姿势','示范视频 · 01:45','#f0edff','#7061d1')}${resource('光线与眼睛','科普视频 · 03:12','#fff0f3','#d7667e')}${resource('眼睛休息一下','儿歌视频 · 02:46','#edf6e9','#719136')}</div></div><div class="modal-foot"><span style="margin-right:auto;color:#8b96a7;font-size:10px">已选择 1 项</span><button class="btn" data-close>取消</button><button class="btn primary" id="addResource">添加到任务路径</button></div>`,true)}
function resource(title,meta,bg,color,selected=false){return `<div class="resource-card ${selected?'selected':''}"><div class="resource-preview" style="--bg:${bg};--color:${color}">▶</div>${selected?'<span class="resource-check">✓</span>':''}<h4>${title}</h4><p>${meta}</p></div>`}

function newPageModal(){openModal(`<div class="modal-head"><h2>添加页面</h2><button class="modal-close" data-close>×</button></div><div class="modal-body"><div class="field-row"><div class="field"><label><b style="color:#e45b62">*</b> 页面名称</label><input id="newPageName" placeholder="请输入页面名称"></div><div class="field"><label><b style="color:#e45b62">*</b> 所属模块</label><select id="newPageModule"><option>快乐成长</option><option>古诗学堂</option><option>英语启蒙</option><option>思维逻辑</option><option>玩转数学</option><option>趣味百科</option><option>故事时间</option></select></div></div><div class="field-row"><div class="field"><label>页面编码</label><input value="PAGE-" placeholder="发布后不可修改"></div><div class="field"><label>页面路由</label><input id="newPageRoute" value="/growth/" placeholder="仅支持小写字母、数字与短横线"></div></div><div class="field"><label><b style="color:#e45b62">*</b> 页面模板</label><div class="radio-row page-template-grid"><div class="radio-card active" data-template>主题入口页</div><div class="radio-card" data-template>横向轮播页</div><div class="radio-card" data-template>路径关卡页</div><div class="radio-card" data-template>场景热点页</div><div class="radio-card" data-template>视频任务页</div><div class="radio-card" data-template>知识详情页</div></div></div><div class="field-row"><div class="field"><label>页面旁白</label><textarea placeholder="进入页面时播放，可保存后在旁白库试听"></textarea></div><div class="field"><label>默认焦点</label><select><option>上次进行中</option><option>第一项未完成</option><option>固定第一项</option></select></div></div><div class="switch-row"><span>创建后进入页面配置</span><i class="switch on" data-toggle></i></div></div><div class="modal-foot"><button class="btn" data-close>取 消</button><button class="btn primary" id="createPageConfirm">确 定</button></div>`,true)}

function moduleEditModal(index=null){const m=index===null?null:modules[index];openModal(`<div class="modal-head"><h2>${m?'编辑':'添加'}模块</h2><button class="modal-close" data-close>×</button></div><div class="modal-body"><div class="field-row"><div class="field"><label><b style="color:#e45b62">*</b> 模块编码</label><input ${m?'disabled':''} value="${m?`MOD-${String(index+1).padStart(2,'0')}`:''}" placeholder="发布后不可修改"></div><div class="field"><label><b style="color:#e45b62">*</b> 模块名称</label><input id="moduleNameDraft" value="${m?m.name:''}" placeholder="请输入模块名称"></div></div><div class="field"><label>模块说明</label><textarea>${m?m.desc:''}</textarea></div><div class="field-row"><div class="field"><label>入口图</label><div class="asset-picker"><span>${m?'module-cover.png':'请选择入口图'}</span><button>上传新图</button></div></div><div class="field"><label>页面背景</label><div class="asset-picker"><span>${m?'module-bg.png':'请选择背景图'}</span><button>上传新图</button></div></div></div><div class="field-row"><div class="field"><label>入口旁白</label><textarea placeholder="请输入旁白文案，保存后生成音频">${m?`欢迎来到${m.name}。`:''}</textarea></div><div class="field"><label>默认焦点</label><select><option>上次进行中</option><option>第一项未完成</option><option>固定第一项</option></select></div></div><div class="field-row"><div class="field"><label>状态</label><select><option>${m?m.status:'草稿'}</option><option>草稿</option><option>待审核</option><option>已发布</option></select></div><div class="field"><label>首页排序</label><input type="number" value="${index===null?10:index+1}"></div></div></div><div class="modal-foot"><button class="btn" data-close>取 消</button><button class="btn primary" id="saveModuleMeta">确 定</button></div>`,true)}

function editQuestionModal(isNew=false){openModal(`<div class="modal-head"><h2>${isNew?'添加':'编辑'}题目</h2><button class="modal-close" data-close>×</button></div><div class="modal-body question-form"><div class="field"><label><b style="color:#e45b62">*</b> 所属游戏</label><select><option>${isNew?'请选择游戏':'礼仪小达人'}</option><option>汉字打怪兽</option><option>视力小卫士</option></select></div><div class="field"><label>题目旁白</label><textarea placeholder="请输入题目旁白文案（保存后自动生成音频）">${isNew?'':'看书时，眼睛离书本约一尺最合适。'}</textarea></div><div class="field-row"><div class="field"><label>题目文字</label><input value="${isNew?'':'看书时，眼睛离书本多远比较合适？'}" placeholder="请输入题目文字"></div><div class="field"><label>是否朗读</label><div class="radio-inline"><label><input type="radio" name="read" checked> 否</label><label><input type="radio" name="read"> 是</label></div></div></div><div class="field-row"><div class="field"><label>题目音频</label><div class="asset-picker"><span>不能使用 TTS 时可手动上传</span><button>上传音频</button></div></div><div class="field"><label>题目图片</label><div class="asset-picker"><span>支持多选</span><button>上传配图</button></div></div></div><div class="field-row"><div class="field"><label>题目背景图</label><div class="asset-picker"><span>bg.png</span><button>上传新图</button></div></div><div class="field"><label>落焦图</label><div class="asset-picker"><span>focus.png</span><button>上传新图</button></div></div></div><div class="field-row"><div class="field"><label>难度等级</label><input type="number" value="1"></div><div class="field"><label>适用年龄段</label><select><option>0-2</option><option>2-4</option><option>4-6</option></select></div></div><div class="field"><label>选项列表</label><button class="add-line-btn">＋ 添加选项</button></div><div class="field"><label>目标项列表</label><button class="add-line-btn">＋ 添加目标项</button></div><div class="field"><label>答案</label><textarea placeholder="请输入答案">${isNew?'':'A'}</textarea></div><div class="field-row"><div class="field"><label>正确答案提示</label><textarea>${isNew?'':'回答正确，真棒！'}</textarea></div><div class="field"><label>错误答案提示</label><textarea>${isNew?'':'再想一想吧。'}</textarea></div></div><div class="field"><label>扩展字段</label><textarea placeholder="请输入扩展字段内容"></textarea></div></div><div class="modal-foot"><button class="btn" data-close>取 消</button><button class="btn primary" id="saveQuestion">确 定</button></div>`,true)}

function filterPages(){let keyword=(document.querySelector('#pageSearch')?.value||'').trim().toLowerCase();let module=document.querySelector('#pageModule')?.value||'';let status=document.querySelector('#pageStatus')?.value||'';let visible=0;document.querySelectorAll('[data-page-row]').forEach(row=>{let ok=(!keyword||(row.dataset.name+row.dataset.route).toLowerCase().includes(keyword))&&(!module||row.dataset.module===module)&&(!status||row.dataset.status===status);row.style.display=ok?'':'none';if(ok)visible++});let count=document.querySelector('#pageCount');if(count)count.textContent=`共 36 个二级页面 · 当前展示 ${visible} 个`}
function filterModules(){let keyword=(document.querySelector('#moduleSearch')?.value||'').trim().toLowerCase();let status=document.querySelector('#moduleStatus')?.value||'';let visible=0;document.querySelectorAll('[data-module-card]').forEach(card=>{let ok=(!keyword||card.dataset.name.toLowerCase().includes(keyword))&&(!status||card.dataset.status===status);card.style.display=ok?'':'none';if(ok)visible++});let count=document.querySelector('#moduleCount');if(count)count.textContent=`共 ${visible} 个模块`}
function selectBuilderBlock(type){document.querySelectorAll('.canvas-block').forEach(x=>x.classList.toggle('selected',x.dataset.canvas===type));document.querySelectorAll('.builder-tree [data-component]').forEach(x=>x.classList.toggle('active',x.dataset.component===type));let names={banner:'顶部主题区',categories:'分类导航',tasks:'推荐任务',list:'内容列表',game:'游戏推荐',video:'视频推荐',campaign:'运营活动'};let title=document.querySelector('#inspectorTitle');if(title)title.textContent=names[type]||'组件属性'}

document.addEventListener('click',e=>{
  const nav=e.target.closest('.nav-item');if(nav){navigate(nav.dataset.page);return}
  const go=e.target.closest('[data-go]');if(go){navigate(go.dataset.go);return}
  const pageEdit=e.target.closest('[data-page-edit]');if(pageEdit){activePageIndex=Number(pageEdit.dataset.pageEdit)||0;navigate('pageEditor');return}
  const pageRowEl=e.target.closest('[data-page-row]');if(pageRowEl&&!e.target.closest('button')&&!e.target.closest('.checkbox')){document.querySelectorAll('[data-page-row]').forEach(x=>x.classList.remove('selected-row'));pageRowEl.classList.add('selected-row');toast('已选择页面',`${pageRowEl.dataset.module} · ${pageRowEl.dataset.name}`);return}
  if(e.target.id==='newPage'){newPageModal();return}
  if(e.target.id==='pageQuery'){filterPages();toast('查询完成','已按当前条件更新页面列表');return}
  if(e.target.id==='pageReset'){let search=document.querySelector('#pageSearch');let mod=document.querySelector('#pageModule');let status=document.querySelector('#pageStatus');if(search)search.value='';if(mod)mod.value='';if(status)status.value='';filterPages();return}
  if(e.target.id==='createPageConfirm'){let name=document.querySelector('#newPageName')?.value.trim();if(!name){toast('请填写页面名称','页面名称不能为空');return}closeModal();toast('二级页面创建成功',`${name} 已创建，正在进入页面装修`);setTimeout(()=>navigate('pageEditor'),450);return}
  if(e.target.id==='copyPage'){toast('页面已复制','已复制“健康卫生”并生成草稿副本');return}
  if(e.target.id==='pageSort'){document.querySelector('#pageTableBody')?.append(...[...document.querySelectorAll('[data-page-row]')].reverse());toast('已进入排序模式','当前页面顺序已反转，用于演示排序效果');return}
  if(e.target.closest('[data-page-more]')){openModal(`<div class="modal-head"><h2>页面操作</h2><button class="modal-close" data-close>×</button></div><div class="modal-body"><div class="activity-list" style="margin-top:0">${activity('⧉','复制为新页面','保留当前页面配置与分类数据','执行')}${activity('▤','查看配置详情','查看当前发布版本的配置字段','查看')}${activity('◷','查看版本记录','比较历史版本并回滚','查看')}</div></div><div class="modal-foot"><button class="btn danger" id="archivePage">停用页面</button><button class="btn" data-close>关闭</button></div>`);return}
  if(e.target.id==='archivePage'){closeModal();toast('页面已停用','原路由将保留，前端不再展示该页面');return}
  const rowCheck=e.target.closest('[data-row-check]');if(rowCheck){rowCheck.classList.toggle('checked');rowCheck.closest('tr')?.classList.toggle('selected-row',rowCheck.classList.contains('checked'));return}
  const checkAll=e.target.closest('[data-check-all]');if(checkAll){checkAll.classList.toggle('checked');document.querySelectorAll('[data-row-check]').forEach(x=>x.classList.toggle('checked',checkAll.classList.contains('checked')));return}
  if(e.target.closest('[data-edit-module]')){navigate('composer');return}
  const editModuleMeta=e.target.closest('[data-edit-module-meta]');if(editModuleMeta){moduleEditModal(Number(editModuleMeta.dataset.editModuleMeta));return}
  if(e.target.id==='addModule'){moduleEditModal();return}
  if(e.target.id==='saveModuleMeta'){let name=document.querySelector('#moduleNameDraft')?.value.trim();if(!name){toast('请填写模块名称','模块名称不能为空');return}closeModal();toast('模块信息已保存',`${name}已加入草稿版本`);return}
  if(e.target.id==='moduleQuery'){filterModules();toast('查询完成','已按当前条件更新模块列表');return}
  if(e.target.id==='moduleReset'){let search=document.querySelector('#moduleSearch');let status=document.querySelector('#moduleStatus');if(search)search.value='';if(status)status.value='';filterModules();return}
  if(['deleteModule','deletePage'].includes(e.target.id)){toast('请选择数据','请先勾选需要删除的记录');return}
  if(e.target.id==='sortModules'){toast('模块排序','拖拽表格行可调整前端首页展示顺序');return}
  if(e.target.closest('[data-module-more]')){toast('模块操作菜单','可复制模块、调整状态或查看版本记录');return}
  if(e.target.id==='mobileMenu'){document.querySelector('#sidebar').classList.toggle('open');return}
  if(e.target.id==='addLevel'){levelEditModal();return}
  const editLevel=e.target.closest('[data-edit-level]');if(editLevel){levelEditModal(Number(editLevel.dataset.editLevel));return}
  const configLevel=e.target.closest('[data-config-level]');if(configLevel){let level=getPageLevels(secondaryPages[activePageIndex]||secondaryPages[0])[Number(configLevel.dataset.configLevel)];toast('进入等级内容配置',`${level.name}可继续关联视频、游戏和列表页`);setTimeout(()=>navigate('composer'),350);return}
  const deleteLevel=e.target.closest('[data-delete-level]');if(deleteLevel){let page=secondaryPages[activePageIndex]||secondaryPages[0];let levels=getPageLevels(page);if(levels.length<=1){toast('至少保留一个等级','当前等级分类不能继续删除');return}let removed=levels.splice(Number(deleteLevel.dataset.deleteLevel),1)[0];renderPageBuilder();toast('等级分类已删除',`${removed.name}已从当前草稿移除`);return}
  if(e.target.id==='saveLevel'){let name=document.querySelector('#levelNameDraft')?.value.trim();if(!name){toast('请填写等级分类名称','等级分类名称不能为空');return}let page=secondaryPages[activePageIndex]||secondaryPages[0];let levels=getPageLevels(page);let raw=document.querySelector('#editingLevelIndex')?.value;let draft={name,id:document.querySelector('#levelCodeDraft')?.value||`LEVEL-0${levels.length+1}`,image:document.querySelector('#levelImageName')?.textContent==='暂未选择图片'?'level_default.png':document.querySelector('#levelImageName')?.textContent,description:document.querySelector('#levelDescriptionDraft')?.value||'',voice:document.querySelector('#levelVoiceDraft')?.value||'',status:document.querySelector('#levelStatusDraft')?.value||'启用'};if(raw==='')levels.push(draft);else levels[Number(raw)]=draft;closeModal();renderPageBuilder();toast('等级分类已保存',`${name}已加入当前页面草稿`);return}
  if(e.target.closest('[data-select-asset]')){let type=e.target.closest('[data-select-asset]').dataset.selectAsset;if(type==='level'&&document.querySelector('#levelImageName')){document.querySelector('#levelImageName').textContent='level_selected.png';toast('等级图片已选择','已从素材库选择 level_selected.png');return}openModal(`<div class="modal-head"><h2>选择页面背景图</h2><button class="modal-close" data-close>×</button></div><div class="modal-body"><div class="asset-choice-grid"><button class="asset-choice selected" data-choose-asset="bg_poetry_hall.png"><i>背景 A</i><span>bg_poetry_hall.png</span></button><button class="asset-choice" data-choose-asset="bg_poetry_lake.png"><i>背景 B</i><span>bg_poetry_lake.png</span></button><button class="asset-choice" data-choose-asset="bg_poetry_garden.png"><i>背景 C</i><span>bg_poetry_garden.png</span></button></div></div><div class="modal-foot"><button class="btn" data-close>取 消</button><button class="btn primary" id="confirmAsset">确 定</button></div>`);return}
  const chooseAsset=e.target.closest('[data-choose-asset]');if(chooseAsset){document.querySelectorAll('[data-choose-asset]').forEach(x=>x.classList.toggle('selected',x===chooseAsset));return}
  if(e.target.id==='confirmAsset'){let chosen=document.querySelector('[data-choose-asset].selected')?.dataset.chooseAsset;closeModal();toast('素材已选择',chosen||'已更新素材');return}
  if(e.target.closest('[data-upload-asset]')){toast('请选择本地文件','支持 PNG、JPG，上传后将自动校验尺寸与大小');return}
  if(e.target.id==='importQuestions'){importModal(1);return}
  if(e.target.id==='addQuestion'){editQuestionModal(true);return}
  if(e.target.id==='viewBatch'){openModal(`<div class="modal-head"><h2>导入记录</h2><button class="modal-close" data-close>×</button></div><div class="modal-body"><div class="table-wrap"><table class="data-table"><thead><tr><th>批次号</th><th>文件名</th><th>导入结果</th><th>操作人</th><th>导入时间</th><th>操作</th></tr></thead><tbody><tr><td>IMP-20260929-03</td><td>汉字闯关题库.xlsx</td><td><span class="tiny-tag green">238 成功 / 2 失败</span></td><td>运营小林</td><td>今天 10:28</td><td><button class="table-action">错误报告</button><button class="table-action">回滚</button></td></tr><tr><td>IMP-20260928-02</td><td>礼仪小达人题库.zip</td><td><span class="tiny-tag green">60 成功</span></td><td>内容小王</td><td>昨天 16:42</td><td><button class="table-action">导入报告</button></td></tr></tbody></table></div></div><div class="modal-foot"><button class="btn" data-close>关 闭</button></div>`,true);return}
  if(e.target.id==='nextImport'||e.target.id==='chooseSample'){importModal(2);return}
  if(e.target.id==='backImport'){importModal(1);return}
  if(e.target.id==='confirmImport'){importModal(3);return}
  if(e.target.id==='addTask'){resourceModal();return}
  const resourceTab=e.target.closest('.resource-tabs button');if(resourceTab){resourceTab.parentElement.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===resourceTab));toast('资源类型已切换',`当前浏览：${resourceTab.textContent}`);return}
  const resourceCard=e.target.closest('.resource-card');if(resourceCard){resourceCard.classList.toggle('selected');let existing=resourceCard.querySelector('.resource-check');if(existing)existing.remove();else resourceCard.insertAdjacentHTML('afterbegin','<span class="resource-check">✓</span>');let count=document.querySelectorAll('.resource-card.selected').length;let label=modal.querySelector('.modal-foot span');if(label)label.textContent=`已选择 ${count} 项`;return}
  if(e.target.id==='addResource'){closeModal();toast('任务已添加','“眼睛的秘密”已加入保护眼睛任务路径末尾');return}
  const chain=e.target.closest('.chain-item');if(chain&&!e.target.closest('button')){document.querySelectorAll('.chain-item').forEach(x=>x.classList.remove('selected'));chain.classList.add('selected');let title=chain.querySelector('h4')?.textContent.replace(/视频|游戏/,'').trim();let small=document.querySelector('.inspector .panel-head small');if(small&&title)small.textContent=`当前：${title.replace(/^\d+\.\s*/,'')}`;return}
  const tree=e.target.closest('.tree-row');if(tree&&tree.closest('.tree')){tree.closest('.tree').querySelectorAll('.tree-row').forEach(x=>x.classList.remove('active'));tree.classList.add('active');toast('内容节点已切换',tree.textContent.replace(/\d+$/,'').trim());return}
  const componentTree=e.target.closest('[data-component]');if(componentTree){selectBuilderBlock(componentTree.dataset.component);return}
  const canvas=e.target.closest('[data-canvas]');if(canvas){selectBuilderBlock(canvas.dataset.canvas);return}
  const addComponent=e.target.closest('[data-add-component]');if(addComponent){let type=addComponent.dataset.addComponent;toast('组件已添加',`${addComponent.textContent.trim()}已添加到页面底部`);selectBuilderBlock(type);return}
  const device=e.target.closest('[data-device]');if(device){device.parentElement.querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===device));let preview=document.querySelector('#devicePreview');if(preview)preview.style.width=device.dataset.device==='tv'?'min(760px,100%)':device.dataset.device==='tablet'?'min(640px,100%)':'min(380px,100%)';toast('预览设备已切换',device.textContent.trim());return}
  const inspectorTab=e.target.closest('[data-inspector-tab]');if(inspectorTab){document.querySelectorAll('[data-inspector-tab]').forEach(x=>x.classList.toggle('active',x===inspectorTab));document.querySelectorAll('[data-inspector-pane]').forEach(x=>x.classList.toggle('active',x.dataset.inspectorPane===inspectorTab.dataset.inspectorTab));return}
  const templateDemo=e.target.closest('[data-template-demo]');if(templateDemo){templateDemo.parentElement.querySelectorAll('.template-mini').forEach(x=>x.classList.toggle('active',x===templateDemo));let preview=document.querySelector('#devicePreview');if(preview)preview.dataset.templateMode=templateDemo.dataset.templateDemo;let map={hub:'主题入口页',carousel:'横向轮播页',path:'路径关卡页',hotspot:'场景热点页',media:'视频任务页',detail:'知识详情页'};let sub=document.querySelector('.page-heading p');if(sub)sub.textContent=`快乐成长 / 健康卫生 · 模板：${map[templateDemo.dataset.templateDemo]} · 自动保存于刚刚`;toast('页面模板已切换',`${map[templateDemo.dataset.templateDemo]}预览已加载`);return}
  const speak=e.target.closest('[data-speak]');if(speak){speakText(speak.dataset.speak);return}
  const speakSource=e.target.closest('[data-speak-source]');if(speakSource){speakText(document.querySelector(`#${speakSource.dataset.speakSource}`)?.value||'');return}
  if(e.target.id==='focusRules'){openModal(`<div class="modal-head"><h2>焦点与遥控器规则</h2><button class="modal-close" data-close>×</button></div><div class="modal-body"><div class="focus-rule-map"><div><b>默认焦点</b><span>保护眼睛</span></div><div><b>← / →</b><span>同组循环切换卡片</span></div><div><b>↑ / ↓</b><span>切换主题区与任务区</span></div><div><b>确认键</b><span>进入详情或开始任务</span></div><div><b>返回键</b><span>返回上一级并记忆焦点</span></div></div><div class="template-tip"><span>ⓘ</span><span>焦点变化时自动播报名称、状态和动态进度，锁定项播报解锁条件。</span></div></div><div class="modal-foot"><button class="btn" data-close>取消</button><button class="btn primary" id="saveFocusRules">保存规则</button></div>`);return}
  if(e.target.id==='saveFocusRules'){closeModal();toast('焦点规则已保存','遥控器方向映射和语音播报规则已更新');return}
  if(e.target.id==='validatePage'){toast('页面校验通过','结构、素材、旁白、焦点路径与解锁规则共 18 项全部通过');return}
  if(e.target.id==='newVoice'){newVoiceModal();return}
  if(e.target.closest('[data-edit-voice]')){newVoiceModal(e.target.closest('[data-voice-row]')?.dataset.text||'');return}
  if(e.target.id==='saveVoice'){closeModal();toast('旁白已保存','已加入待审核列表，可绑定页面或焦点元素');return}
  if(e.target.id==='voiceExport'){toast('旁白脚本已导出','正在生成 XLSX 文件');return}
  if(e.target.id==='voiceImport'){toast('批量导入已就绪','支持 XLSX 脚本和 ZIP 音频包');return}
  const toggle=e.target.closest('[data-toggle]');if(toggle){toggle.classList.toggle('on');return}
  const radio=e.target.closest('.radio-card');if(radio){radio.parentElement.querySelectorAll('.radio-card').forEach(x=>x.classList.toggle('active',x===radio));return}
  if(e.target.id==='applyComponent'){let title=document.querySelector('#heroTitleInput')?.value;let desc=document.querySelector('#heroDescInput')?.value;let hero=document.querySelector('.hero-block');if(hero){hero.querySelector('h3').textContent=title||'未命名主题';hero.querySelector('p').textContent=desc||''}toast('组件设置已应用','页面预览已同步更新');return}
  if(e.target.id==='savePageDraft'){toast('页面草稿已保存','背景图、旁白与等级分类配置已保存');return}
  if(e.target.id==='savePage'){let page=secondaryPages[activePageIndex]||secondaryPages[0];toast('页面已保存并提交审核',`${page.name}已生成新的待审核版本`);return}
  if(e.target.id==='deleteComponent'){let selected=document.querySelector('.canvas-block.selected');if(selected){selected.style.display='none';toast('组件已从页面移除','保存前可以使用撤销恢复')};return}
  if(['undoAction','redoAction','toggleGrid','refreshPreview'].includes(e.target.id)){toast('画布操作已执行',e.target.textContent.trim());return}
  if(e.target.closest('[data-close]')){closeModal();return}
  if(e.target.id==='saveDraft'){toast('草稿已保存','所有内容变更已保存，尚未影响线上版本');return}
  if(e.target.id==='submitReview'){toast('已提交审核','版本 V2.4 的内容变更已进入审核队列');return}
  if(e.target.id==='exportQuestions'){toast('导出任务已创建','正在生成 XLSX 文件，完成后将自动下载');return}
  if(e.target.id==='exportErrors'||e.target.id==='downloadReport'){toast('文件已生成','演示原型：下载任务创建成功');return}
  if(e.target.id==='validateRelease'){toast('上线校验通过','12 项必检规则全部通过，可以安全发布');e.target.textContent='✓ 12/12 校验通过';return}
  if(e.target.id==='publishRelease'){openModal(`<div class="modal-head"><h2>确认发布 V2.4</h2><button class="modal-close" data-close>×</button></div><div class="modal-body"><div class="template-tip" style="margin-top:0;background:#fff5e8;color:#875b28"><span>!</span><span>发布后将影响约 12,480 名用户。系统会保留 V2.3 作为可回滚版本。</span></div><div style="padding:18px 0 3px;font-size:12px;line-height:2;color:#536075"><b>变更范围：</b>4 个模块、18 项内容、240 道题目<br><b>发布时间：</b>立即发布<br><b>回滚策略：</b>异常时一键回滚至 V2.3</div></div><div class="modal-foot"><button class="btn" data-close>取消</button><button class="btn primary" id="confirmPublish">确认并发布</button></div>`);return}
  if(e.target.id==='confirmPublish'){closeModal();toast('版本发布任务已开始','V2.4 正在发布，预计 1—2 分钟完成');return}
  if(e.target.id==='previewModule'){toast('已生成预览','前端预览链接有效期为 2 小时');return}
  if(e.target.id==='createRelease'){toast('已进入创建流程','演示原型已保留完整创建入口');return}
  if(e.target.classList.contains('table-action')&&e.target.textContent.trim()==='编辑'){editQuestionModal();return}
  if(e.target.id==='saveQuestion'){closeModal();toast('题目已保存','Q-3862 的修改已加入待发布版本');return}
  if(e.target.closest('.pages button')){let button=e.target.closest('button');button.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('active'));if(!['‹','›','…'].includes(button.textContent.trim()))button.classList.add('active');toast('列表已翻页',`当前页：${button.textContent.trim()}`);return}
  if(e.target.closest('.btn,.icon-more,.text-link,.table-action')){toast('交互已响应','此操作在原型中已进入对应流程');return}
});
document.addEventListener('input',e=>{if(e.target.id==='pageSearch')filterPages();if(e.target.id==='moduleSearch')filterModules();if(e.target.id==='heroTitleInput'){let h=document.querySelector('.hero-block h3');if(h)h.textContent=e.target.value}if(e.target.id==='heroDescInput'){let p=document.querySelector('.hero-block p');if(p)p.textContent=e.target.value}});
document.addEventListener('change',e=>{if(e.target.id==='pageModule'||e.target.id==='pageStatus')filterPages();if(e.target.id==='moduleStatus')filterModules();if(e.target.id==='previewState'){let preview=document.querySelector('#devicePreview');if(preview){preview.classList.remove('state-progress','state-new','state-done','state-locked');preview.classList.add(`state-${e.target.value}`)}let labels={progress:['进行中 1/10','已完成','未开始'],new:['未开始','未开始','未开始'],done:['已完成 10/10','已完成','已完成'],locked:['已锁定','已锁定','已锁定']};document.querySelectorAll('.category-tile small').forEach((x,i)=>x.textContent=labels[e.target.value][i]||labels[e.target.value][0]);toast('用户状态已切换',e.target.options[e.target.selectedIndex].text)}});
modalBackdrop.addEventListener('click',e=>{if(e.target===modalBackdrop)closeModal()});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();let cards=[...document.querySelectorAll('.category-tile')];if(cards.length&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();let current=Math.max(0,cards.indexOf(document.activeElement));let next=e.key==='ArrowRight'?(current+1)%cards.length:(current-1+cards.length)%cards.length;cards[next].focus();speakText(cards[next].dataset.speak)}if(e.key==='Enter'&&document.activeElement?.classList.contains('category-tile'))speakText(document.activeElement.dataset.speak)});
navigate('dashboard');
